# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
