# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20170806_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='profile_pic/profile.png', upload_to='profile_pic'),
        ),
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
