# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0004_notify'),
    ]

    operations = [
        migrations.AddField(
            model_name='notify',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
