# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0005_notify_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='notify',
            name='noti_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
