# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_is_closed'),
        ('infos', '0006_notify_noti_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notify',
            name='noti_url',
        ),
        migrations.AddField(
            model_name='notify',
            name='noti_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='posts.Post'),
        ),
        migrations.AddField(
            model_name='notify',
            name='rating',
            field=models.IntegerField(default=-1),
        ),
    ]
