# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0008_auto_20170813_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notify',
            name='noti_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
