# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 04:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0010_auto_20170813_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notify',
            name='noti_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
